# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'annotation.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 888)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(900, 10, 151, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ratButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.ratButton.setObjectName("ratButton")
        self.verticalLayout.addWidget(self.ratButton)
        self.nonratButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.nonratButton.setObjectName("nonratButton")
        self.verticalLayout.addWidget(self.nonratButton)
        self.nonobjectButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.nonobjectButton.setObjectName("nonobjectButton")
        self.verticalLayout.addWidget(self.nonobjectButton)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.truncetCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.truncetCheckBox.setObjectName("truncetCheckBox")
        self.verticalLayout.addWidget(self.truncetCheckBox)
        self.occludCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.occludCheckBox.setObjectName("occludCheckBox")
        self.verticalLayout.addWidget(self.occludCheckBox)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(900, 450, 151, 105))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.confirmAndAnnocateButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.confirmAndAnnocateButton.setObjectName("confirmAndAnnocateButton")
        self.verticalLayout_3.addWidget(self.confirmAndAnnocateButton)
        self.nextPicButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.nextPicButton.setObjectName("nextPicButton")
        self.verticalLayout_3.addWidget(self.nextPicButton)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_3)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(900, 270, 152, 156))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.frontalButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.frontalButton.setObjectName("frontalButton")
        self.verticalLayout_2.addWidget(self.frontalButton)
        self.tailButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.tailButton.setObjectName("tailButton")
        self.verticalLayout_2.addWidget(self.tailButton)
        self.sideButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.sideButton.setObjectName("sideButton")
        self.verticalLayout_2.addWidget(self.sideButton)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 871, 671))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget_4)
        self.graphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_4.addWidget(self.graphicsView)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 690, 871, 121))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.infoTextBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_5)
        self.infoTextBrowser.setObjectName("infoTextBrowser")
        self.verticalLayout_5.addWidget(self.infoTextBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSelectFloader = QtWidgets.QAction(MainWindow)
        self.actionSelectFloader.setObjectName("actionSelectFloader")
        self.actionSelectFile = QtWidgets.QAction(MainWindow)
        self.actionSelectFile.setObjectName("actionSelectFile")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.openVideo = QtWidgets.QAction(MainWindow)
        self.openVideo.setObjectName("openVideo")
        self.menuFile.addAction(self.actionSelectFloader)
        self.menuFile.addAction(self.actionSelectFile)
        self.menuFile.addAction(self.actionClose)
        self.menu.addAction(self.openVideo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像标记程序"))
        self.label.setText(_translate("MainWindow", "必选："))
        self.ratButton.setText(_translate("MainWindow", "标记鼠兔"))
        self.nonratButton.setText(_translate("MainWindow", "标记非鼠兔目标"))
        self.nonobjectButton.setText(_translate("MainWindow", "无前景目标"))
        self.label_2.setText(_translate("MainWindow", "可选："))
        self.truncetCheckBox.setText(_translate("MainWindow", "目标被遮挡"))
        self.occludCheckBox.setText(_translate("MainWindow", "目标难以辨认"))
        self.confirmAndAnnocateButton.setText(_translate("MainWindow", "确认并开始标记"))
        self.nextPicButton.setText(_translate("MainWindow", "完成/进行下一张"))
        self.label_4.setText(_translate("MainWindow", "可选："))
        self.label_3.setText(_translate("MainWindow", "观察目标的视角："))
        self.frontalButton.setText(_translate("MainWindow", "正面"))
        self.tailButton.setText(_translate("MainWindow", "尾部"))
        self.sideButton.setText(_translate("MainWindow", "侧面"))
        self.menuFile.setTitle(_translate("MainWindow", "图片处理"))
        self.menu.setTitle(_translate("MainWindow", "视频处理"))
        self.actionSelectFloader.setText(_translate("MainWindow", "打开图片文件夹"))
        self.actionSelectFloader.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSelectFile.setText(_translate("MainWindow", "打开图片"))
        self.actionSelectFile.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionClose.setText(_translate("MainWindow", "关闭程序"))
        self.actionClose.setShortcut(_translate("MainWindow", "Esc"))
        self.openVideo.setText(_translate("MainWindow", "打开并转换"))
        self.openVideo.setShortcut(_translate("MainWindow", "Alt+V"))

